FROM node:12.2-alpine

# 作者
LABEL maintainer="fizzday <fizzday@yeah.net>" \
        Description="nodejs12.2 alpine3.9"

WORKDIR /var/www

RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
